# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            trueSKY Documentation
tagline:          ''
description:      ''
url:              https://docs.simul.co
baseurl:          /

author:
  name:           ''
  url:            

# Custom vars
version:          2.1.0

array: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1